### PR TITLE
PEP-8 tidying, some simplifying

### PR DESCRIPTION
**Pull request by nicktimko**
Extends the compat branch and tweaks the formatting so it's a bit more standard.

### CODE REVIEW

**Comment by nicktimko** [comment]
Rebased this a bit on top of the updates. Unified the spacing style as per PEP-8, CRLF/LF endings, and opted for comprehensions to remove most lambdas.

**Comment by nicktimko** [comment]
Do you have any interest in merging this? 

I'm hoping to end up with a simple `where` tool that will work cross-platform (incl. Windows), but given the pace of merging changes, that doesn't seem likely.

**Comment by hweickert** [comment]
Hi Nick,

I do like and agree with most of your ideas and changes. Thank you for that!

Before we further extend the functionality, I would like to have tests that cover the behavior of `_gen_possible_matches()`.
Currently I don't have much time to take care of this. Do you think you could create those?

Regarding the pep8/style stuff:
I recently came across https://pypi.python.org/pypi/flake8. It would be neat if 'setup.cfg' had this section:

```
[flake8]
ignore =
    E201,
    E202,
    E501,
    E222,
    E241,
    E271,
    E303
```

If your IDE/Editor makes use of this, then you might be less tempted to fix some style aspects which I would like the project to follow. Would this work for you?
(http://pep8.readthedocs.io/en/latest/intro.html#error-codes)

Thanks again for your patience and efforts!

Henry

**Comment by nicktimko** [comment]
Yeah, I'll whip up some tests.

A consistent style is fine if it deviates from the standard baseline, but the style _isn't_ consistent. Different line endings, spaces for function arguments, etc.

**Comment by nicktimko** [comment]
PR should be good to go. Regarding formatting, currently with the edits it's _consistent_. To modify the "defaults", you could use a tool like `pycodestyle` and customize the rules. Ignoring so many errors could just result in things being inconsistent again.

**Pull request closed without merging**
